module.exports = function(grunt){

  //region Configuration{
    grunt.initConfig({
      concat: { 
        build:{
          files:[{
            src:['assets/eventually/js/*.js'],
            dest:'dist/js/eventually/eventually.js'
            },
            {
              src:['assets/gallery/js/*.js'],
              dest:'dist/js/gallery/gallery.js'
            },
            {
              src:['assets/home/js/*.js'],
              dest:'dist/js/home/home.js'
            },
            {
              src:['assets/navbar/js/*.js'],
              dest:'dist/js/navbar/navbar.js'
            },
            {
              src:['assets/projects/js/*.js'],
              dest:'dist/js/projects/projects.js'
            },
            {
              src:['assets/eventually/css/*.css'],
              dest:'dist/css/eventually/eventually.css'
            },
            {
              src:['assets/gallery/css/*.css'],
              dest:'dist/css/gallery/gallery.css'
            },
            {
              src:['assets/home/css/*.css'],
              dest:'dist/css/home/home.css'
            },
            {
              src:['assets/navbar/css/*.css'],
              dest:'dist/css/navbar/navbar.css'
            },
            {
              src:['assets/projects/css/*.css'],
              dest:'dist/css/projects/projects.css'
            }
          ]
        }
      },
      uglify:{ //TODO fazer para todos os JS e CSS 
        build:{
          files:[{
            src:['dist/js/eventually/*.js'],
            dest:'dist/js/eventually/eventually.js'
            },
            {
              src:['dist/js/gallery/*.js'],
              dest:'dist/js/gallery/gallery.js'
            },
            {
              src:['dist/js/home/*.js'],
              dest:'dist/js/home/home.js'
            },
            {
              src:['dist/js/navbar/*.js'],
              dest:'dist/js/navbar/navbar.js'
            },
            {
              src:['dist/js/projects/*.js'],
              dest:'dist/js/projects/projects.js'
            },
            {
              src:['dist/css/eventually/*.css'],
              dest:'dist/css/eventually/eventually.css'
            },
            {
              src:['dist/css/gallery/*.css'],
              dest:'dist/css/gallery/gallery.css'
            },
            {
              src:['dist/css/home/*.css'],
              dest:'dist/css/home/home.css'
            },
            {
              src:['dist/css/navbar/*.css'],
              dest:'dist/css/navbar/navbar.css'
            },
            {
              src:['dist/css/projects/*.css'],
              dest:'dist/css/projects/projects.css'
            }
          ]
        }
      }      
    });

  //regionLoadPlugins
    
    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-contrib-uglify');
};